services:
  test:
    image: ghcr.io/salsadigitalauorg/ansible-test:latest
    volumes:
      - ./api:/usr/share/ansible/collections/ansible_collections/lagoon/api
    working_dir: /usr/share/ansible/collections/ansible_collections/lagoon/api

  graphql-mock:
    build:
      context: .
      dockerfile: .docker/Dockerfile.graphql-mock
    command: ["npm", "start"]
    ports:
      - 4000
