name: Build ansible docs
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Log level'
        required: true

    outputs:
      artifact-name:
        description: The same artifact name as passed in, available as an output.
        value: ${{ inputs.artifact-name }}
      artifact-url:
        description: The URL to the build artifacts.
        value: ${{ jobs.build-ansible-docs.outputs.artifact-url }}

jobs:
  build-ansible-docs:
    name: Build Ansible Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-url: ${{ steps.build-head.outputs.artifact-url }}
    steps:
      - name: Variable setup
        id: vars
        uses: actions/github-script@v7
        with:
          script: |
            const inputs = ${{ toJSON(inputs) }}
            var colpath = inputs['collection-path']
            var colname = inputs['collection-name']

            if (colname == '') {
                colname = process.env.GITHUB_REPOSITORY.split('/')[1]
            }

            if (colpath == '') {
                colpath = colname.replace('.', '/')
            }

            core.exportVariable('ANSIBLE_COLLECTIONS_PATHS', process.env.GITHUB_WORKSPACE)

            const checkoutPath = `ansible_collections/${colpath}`

            core.setOutput('col-name', colname)
            core.setOutput('col-path', colpath)
            core.setOutput('checkout-path', checkoutPath)

            var initPath = '${{ runner.temp }}/docsbuild'
            var skipInit = false

            if (inputs['init-dest-dir'] != '') {
                initPath = `${checkoutPath}/${inputs['init-dest-dir']}`
                skipInit = true
            }

            core.setOutput('init-dir', initPath)
            core.setOutput('skip-init', skipInit)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}

      - name: Install Ansible
        run: pip install https://github.com/ansible/ansible/archive/${{ inputs.ansible-ref }}.tar.gz --disable-pip-version-check

      - name: Install extra collections
        shell: bash
        run: |
          if [[ "${{ inputs.extra-collections }}" != "" ]] ; then
            ansible-galaxy collection install ${{ inputs.extra-collections }}
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ steps.vars.outputs.checkout-path }}
          ref: ${{ inputs.build-ref }}

      - name: Initialize the build environment
        id: init
        uses: ansible-community/github-docs-build/actions/ansible-docs-build-init@main
        with:
          collections: ${{ steps.vars.outputs.col-name }}
          dest-dir: ${{ steps.vars.outputs.init-dir }}
          skip-init: ${{ steps.vars.outputs.skip-init }}
          antsibull-docs-version: '${{ inputs.init-antsibull-docs-version }}'
          antsibull-docs-repository: '${{ inputs.init-antsibull-docs-repository }}'
          lenient: ${{ inputs.init-lenient }}
          fail-on-error: ${{ inputs.init-fail-on-error }}
          provide-link-targets: ${{ inputs.provide-link-targets }}
          intersphinx-links: ${{ inputs.intersphinx-links }}
          squash-hierarchy: ${{ inputs.squash-hierarchy }}
          index-rst-source: ${{ inputs.init-index-rst-source }}
          project: ${{ inputs.init-project }}
          copyright: ${{ inputs.init-copyright }}
          title: ${{ inputs.init-title }}
          html-short-title: ${{ inputs.init-html-short-title }}
          extra-conf: ${{ inputs.init-extra-conf }}
          extra-html-context: ${{ inputs.init-extra-html-context }}
          extra-html-theme-options: ${{ inputs.init-extra-html-theme-options }}
          append-conf-py: ${{ inputs.init-append-conf-py }}

      - name: Build
        id: build
        uses: ansible-community/github-docs-build/actions/ansible-docs-build-html@main
        with:
          build-script: ${{ steps.init.outputs.build-script }}
          build-html: ${{ steps.init.outputs.build-html }}
          artifact-name: ${{ inputs.artifact-name }}
          artifact-upload: ${{ inputs.artifact-upload }}
